version: "3"

services:

  app:
    build: .
    restart: always
    ports: 
      - ${EXTERNAL_APP_PORT}:${NGINX_PORT}
    environment:
      - ENV_TYPE=${ENV_TYPE}
      - API_BASE_URL=${API_BASE_URL}
      - COOKIE_USER_ID_NAME=${COOKIE_USER_ID_NAME}
      - COOKIE_AUTH_TOKEN_NAME=${COOKIE_AUTH_TOKEN_NAME}